### PR TITLE
Create 20191228-murata2makoto-JSON-or-XML-in-a-ZIP-package.md

### PR DESCRIPTION
**Pull request by murata2makoto**
Just a starter.

### CODE REVIEW

**Comment by behdad** [comment]
This is not a good idea in my opinion.  Will increase font loading time & memory consumption *significantly* for no good benefit; also file size.

**Comment by murata2makoto** [comment]
OOXML documents are much more compact than binary MS Office documents.  Unless some experiment is carried out, I do not believe that file size will be a problem.  Textual representations have obvious advantages: easier to browse and modify.  The industry has moved away from ASN.1 to XML, JSON, and so forth.

**Comment by behdad** [comment]
> OOXML documents are much more compact than binary MS Office documents. Unless some experiment is carried out, I do not believe that file size will be a problem. Textual representations have obvious advantages: easier to browse and modify. The industry has moved away from ASN.1 to XML, JSON, and so forth.

That's a lot of mixing up things.  Rest of my comments are not addressed either.

**Comment by behdad** [comment]
Let me ask this way: what problem are you trying to solve?

**Comment by behdad** [comment]
I just checked your bio.  *You* should know better that yes, indeed, XML is great for representing "documents" where text is the primary form of content.  Fonts are not such objects though.  Would you use XML to represent images?  Audio/video?

**Comment by murata2makoto** [comment]
There are already several XML representations of fonts.  I think that this is because binary fonts are harder to browse and modify.  In the area of document formats, textual representations combined with ZIP have overshadowed binary representations.  Why do fonts continue to use binary representations?

**Comment by murata2makoto** [comment]
I would certainly prefer textual representations for font features and metadata.   Tons of numbers might be different, though.

**Comment by behdad** [comment]
You are missing the point.

XML is good for authoring format.  Binary font files are a delivery format.

**Comment by behdad** [comment]
At any rate, since no one is willing to make this happen, this discussion is completely moot.

**Comment by murata2makoto** [comment]
I intend to raise this issue from the JP SC34 mirror.  EPUB is a delivery format.  Arguably, OOXML and ODF are used for delivery.

**Comment by be5invis** [comment]
I dislike this.

A delivered font should be simple and straight, and easy to interpret (layout, render, etc.) Therefore, a ZIP with XML inside it is almost the worst option for this purpose. (And that's why I really dislike CFF -- their interpreters are hard to implement.)

XML, JSON and all the general but complex stuff should be only used when designing fonts.

**Comment by behdad** [comment]
Right.  Fonts need to be random-access.

**Comment by be5invis** [comment]
I’d like to reject this proposal. A more valuable discussion may be creating a textual representation of OpenType fonts — Well, TTX is already there.

**Pull request closed without merging**
